/*
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.lev4rec.ui.internal.Lev4recActivator;

public class RsDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Lev4recActivator.getInstance().getInjector("org.xtext.lev4recgrammar.first.RsDsl");
	}

}
