/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deep NN</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getNumEpochs <em>Num Epochs</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getLearningRate <em>Learning Rate</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getMiniBatchSize <em>Mini Batch Size</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getNumHiddenLayer <em>Num Hidden Layer</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getDeepNN()
 * @model
 * @generated
 */
public interface DeepNN extends RecommendationSystem
{
  /**
   * Returns the value of the '<em><b>Num Epochs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Epochs</em>' attribute.
   * @see #setNumEpochs(int)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getDeepNN_NumEpochs()
   * @model
   * @generated
   */
  int getNumEpochs();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getNumEpochs <em>Num Epochs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Epochs</em>' attribute.
   * @see #getNumEpochs()
   * @generated
   */
  void setNumEpochs(int value);

  /**
   * Returns the value of the '<em><b>Learning Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Learning Rate</em>' attribute.
   * @see #setLearningRate(int)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getDeepNN_LearningRate()
   * @model
   * @generated
   */
  int getLearningRate();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getLearningRate <em>Learning Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Learning Rate</em>' attribute.
   * @see #getLearningRate()
   * @generated
   */
  void setLearningRate(int value);

  /**
   * Returns the value of the '<em><b>Mini Batch Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mini Batch Size</em>' attribute.
   * @see #setMiniBatchSize(int)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getDeepNN_MiniBatchSize()
   * @model
   * @generated
   */
  int getMiniBatchSize();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getMiniBatchSize <em>Mini Batch Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mini Batch Size</em>' attribute.
   * @see #getMiniBatchSize()
   * @generated
   */
  void setMiniBatchSize(int value);

  /**
   * Returns the value of the '<em><b>Num Hidden Layer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Hidden Layer</em>' attribute.
   * @see #setNumHiddenLayer(int)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getDeepNN_NumHiddenLayer()
   * @model
   * @generated
   */
  int getNumHiddenLayer();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.DeepNN#getNumHiddenLayer <em>Num Hidden Layer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Hidden Layer</em>' attribute.
   * @see #getNumHiddenLayer()
   * @generated
   */
  void setNumHiddenLayer(int value);

} // DeepNN
