/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency Manager</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getDependencyManager()
 * @model
 * @generated
 */
public interface DependencyManager extends DataSource
{
} // DependencyManager
