/**
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filtering RS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getFilteringRSAlgorithm <em>Filtering RS Algorithm</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getSimilarityCalculator <em>Similarity Calculator</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getCutoff <em>Cutoff</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getNeighborhood <em>Neighborhood</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getFilteringRS()
 * @model
 * @generated
 */
public interface FilteringRS extends RecommendationSystem
{
  /**
   * Returns the value of the '<em><b>Filtering RS Algorithm</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRSAlgorithm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filtering RS Algorithm</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.FilteringRSAlgorithm
   * @see #setFilteringRSAlgorithm(FilteringRSAlgorithm)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getFilteringRS_FilteringRSAlgorithm()
   * @model
   * @generated
   */
  FilteringRSAlgorithm getFilteringRSAlgorithm();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getFilteringRSAlgorithm <em>Filtering RS Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filtering RS Algorithm</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.FilteringRSAlgorithm
   * @see #getFilteringRSAlgorithm()
   * @generated
   */
  void setFilteringRSAlgorithm(FilteringRSAlgorithm value);

  /**
   * Returns the value of the '<em><b>Similarity Calculator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.lowcoders.SimilarityFunction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Similarity Calculator</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.SimilarityFunction
   * @see #setSimilarityCalculator(SimilarityFunction)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getFilteringRS_SimilarityCalculator()
   * @model
   * @generated
   */
  SimilarityFunction getSimilarityCalculator();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getSimilarityCalculator <em>Similarity Calculator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Similarity Calculator</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.SimilarityFunction
   * @see #getSimilarityCalculator()
   * @generated
   */
  void setSimilarityCalculator(SimilarityFunction value);

  /**
   * Returns the value of the '<em><b>Cutoff</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cutoff</em>' attribute.
   * @see #setCutoff(int)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getFilteringRS_Cutoff()
   * @model
   * @generated
   */
  int getCutoff();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getCutoff <em>Cutoff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cutoff</em>' attribute.
   * @see #getCutoff()
   * @generated
   */
  void setCutoff(int value);

  /**
   * Returns the value of the '<em><b>Neighborhood</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neighborhood</em>' attribute.
   * @see #setNeighborhood(int)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getFilteringRS_Neighborhood()
   * @model
   * @generated
   */
  int getNeighborhood();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.FilteringRS#getNeighborhood <em>Neighborhood</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neighborhood</em>' attribute.
   * @see #getNeighborhood()
   * @generated
   */
  void setNeighborhood(int value);

} // FilteringRS
