/**
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GUI Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getGUIElement()
 * @model
 * @generated
 */
public interface GUIElement extends EObject
{
} // GUIElement
