/**
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proactive Handler</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.ProactiveHandler#isCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getProactiveHandler()
 * @model
 * @generated
 */
public interface ProactiveHandler extends RecommendationHandler
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(boolean)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getProactiveHandler_Condition()
   * @model
   * @generated
   */
  boolean isCondition();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.ProactiveHandler#isCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #isCondition()
   * @generated
   */
  void setCondition(boolean value);

} // ProactiveHandler
