/**
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rating</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.Rating#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRating()
 * @model
 * @generated
 */
public interface Rating extends Feedback
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.lowcoders.RatingType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.RatingType
   * @see #setType(RatingType)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRating_Type()
   * @model
   * @generated
   */
  RatingType getType();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.Rating#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.RatingType
   * @see #getType()
   * @generated
   */
  void setType(RatingType value);

} // Rating
