/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recommendation System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getGenerator <em>Generator</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getSettings <em>Settings</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getScope <em>Scope</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getContext <em>Context</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRecommendationSystem()
 * @model
 * @generated
 */
public interface RecommendationSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRecommendationSystem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Generator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.lowcoders.PyLibType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generator</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.PyLibType
   * @see #setGenerator(PyLibType)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRecommendationSystem_Generator()
   * @model
   * @generated
   */
  PyLibType getGenerator();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getGenerator <em>Generator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generator</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.PyLibType
   * @see #getGenerator()
   * @generated
   */
  void setGenerator(PyLibType value);

  /**
   * Returns the value of the '<em><b>Settings</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSetting}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Settings</em>' containment reference list.
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRecommendationSystem_Settings()
   * @model containment="true"
   * @generated
   */
  EList<RecommendationSetting> getSettings();

  /**
   * Returns the value of the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' containment reference.
   * @see #setScope(RecommendedItem)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRecommendationSystem_Scope()
   * @model containment="true"
   * @generated
   */
  RecommendedItem getScope();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getScope <em>Scope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' containment reference.
   * @see #getScope()
   * @generated
   */
  void setScope(RecommendedItem value);

  /**
   * Returns the value of the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' containment reference.
   * @see #setContext(RecommendationContext)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getRecommendationSystem_Context()
   * @model containment="true"
   * @generated
   */
  RecommendationContext getContext();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem#getContext <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' containment reference.
   * @see #getContext()
   * @generated
   */
  void setContext(RecommendationContext value);

} // RecommendationSystem
