/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Traversable Graph</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getTraversableGraph()
 * @model
 * @generated
 */
public interface TraversableGraph extends PresentationLayer
{
} // TraversableGraph
