/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Web IService</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.lowcoders.WebIService#getLibrary <em>Library</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getWebIService()
 * @model
 * @generated
 */
public interface WebIService extends PresentationLayer
{
  /**
   * Returns the value of the '<em><b>Library</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.lowcoders.WebInterfaceLibrary}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Library</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.WebInterfaceLibrary
   * @see #setLibrary(WebInterfaceLibrary)
   * @see org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage#getWebIService_Library()
   * @model
   * @generated
   */
  WebInterfaceLibrary getLibrary();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.lowcoders.WebIService#getLibrary <em>Library</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Library</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.lowcoders.WebInterfaceLibrary
   * @see #getLibrary()
   * @generated
   */
  void setLibrary(WebInterfaceLibrary value);

} // WebIService
