/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.xtext.lev4recgrammar.first.lowcoders.Evaluation;
import org.xtext.lev4recgrammar.first.lowcoders.FeedbackComponent;
import org.xtext.lev4recgrammar.first.lowcoders.PresentationLayer;
import org.xtext.lev4recgrammar.first.lowcoders.RSModel;
import org.xtext.lev4recgrammar.first.lowcoders.RecommendationSystem;
import org.xtext.lev4recgrammar.first.lowcoders.UnsupervisedDataset;
import org.xtext.lev4recgrammar.first.lowcoders.ValidationTechnique;
import org.xtext.lev4recgrammar.first.services.RsDslGrammarAccess;

@SuppressWarnings("all")
public class RsDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RsDslGrammarAccess _rsDslGrammarAccess;
  
  protected void _format(final RSModel rSModel, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(rSModel).keyword("{"), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("}"), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(rSModel.getDataset()).keyword("{"), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel.getDataset()).keyword("}"), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.allRegionsFor(rSModel.getDataset()).keyword("]"), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("preprocessing"), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel.getDataset()).keyword("dataStructure"), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel.getDataset()).keyword("path"), _function_7);
    document.<PresentationLayer>format(rSModel.getPresentationLayer());
    document.<Evaluation>format(rSModel.getEvaluation());
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("dataStructure"), _function_8);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("dependatVariable"), _function_9);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("indipendentVariables"), _function_10);
    final Procedure1<IHiddenRegionFormatter> _function_11 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("presentationLayer"), _function_11);
    final Procedure1<IHiddenRegionFormatter> _function_12 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel).keyword("validationTechnique"), _function_12);
    final Procedure1<IHiddenRegionFormatter> _function_13 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(rSModel.getEvaluation()).keyword("library"), _function_13);
    document.<RecommendationSystem>format(rSModel.getRecommendationSystem());
    document.<FeedbackComponent>format(rSModel.getFeedback());
  }
  
  protected void _format(final Evaluation evaluation, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(evaluation).keyword("{"), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(evaluation).keyword("}"), _function_1);
    EList<ValidationTechnique> _validationTechnique = evaluation.getValidationTechnique();
    for (final ValidationTechnique validationTechnique : _validationTechnique) {
      document.<ValidationTechnique>format(validationTechnique);
    }
  }
  
  protected void _format(final RecommendationSystem recsys, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(recsys).keyword("{"), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(recsys).keyword("}"), _function_1);
  }
  
  protected void _format(final UnsupervisedDataset dataset, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(dataset).keyword("dataStructure"), _function);
  }
  
  public void format(final Object dataset, final IFormattableDocument document) {
    if (dataset instanceof XtextResource) {
      _format((XtextResource)dataset, document);
      return;
    } else if (dataset instanceof UnsupervisedDataset) {
      _format((UnsupervisedDataset)dataset, document);
      return;
    } else if (dataset instanceof Evaluation) {
      _format((Evaluation)dataset, document);
      return;
    } else if (dataset instanceof RSModel) {
      _format((RSModel)dataset, document);
      return;
    } else if (dataset instanceof RecommendationSystem) {
      _format((RecommendationSystem)dataset, document);
      return;
    } else if (dataset instanceof EObject) {
      _format((EObject)dataset, document);
      return;
    } else if (dataset == null) {
      _format((Void)null, document);
      return;
    } else if (dataset != null) {
      _format(dataset, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(dataset, document).toString());
    }
  }
}
