/*
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.lev4rec.ui.internal.Lev4recActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Lev4recActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Lev4recActivator activator = Lev4recActivator.getInstance();
		return activator != null ? activator.getInjector(Lev4recActivator.ORG_XTEXT_LEV4RECGRAMMAR_FIRST_RSDSL) : null;
	}

}
