/*
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.lev4recgrammar.first.RsDslRuntimeModule;
import org.xtext.lev4recgrammar.first.RsDslStandaloneSetup;
import org.xtext.lev4recgrammar.first.ide.RsDslIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class RsDslWebSetup extends RsDslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RsDslRuntimeModule(), new RsDslIdeModule(), new RsDslWebModule()));
	}
	
}
