/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.rsDsl.BugTrackingSystem;
import org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bug Tracking System</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BugTrackingSystemImpl extends DataSourceImpl implements BugTrackingSystem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BugTrackingSystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RsDslPackage.Literals.BUG_TRACKING_SYSTEM;
  }

} //BugTrackingSystemImpl
