/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.lev4recgrammar.first.rsDsl.GUIElement;
import org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>GUI Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GUIElementImpl extends MinimalEObjectImpl.Container implements GUIElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GUIElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RsDslPackage.Literals.GUI_ELEMENT;
  }

} //GUIElementImpl
