/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage;
import org.xtext.lev4recgrammar.first.rsDsl.UnsupervisedDataset;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Unsupervised Dataset</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UnsupervisedDatasetImpl extends DatasetImpl implements UnsupervisedDataset
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnsupervisedDatasetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RsDslPackage.Literals.UNSUPERVISED_DATASET;
  }

} //UnsupervisedDatasetImpl
