/*
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RsDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRsDslWebModule extends DefaultWebModule {

}
