/*
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RsDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/lev4recgrammar/first/parser/antlr/internal/InternalRsDsl.tokens");
	}
}
