/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.lowcoders.CommunicationChannel;
import org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Communication Channel</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CommunicationChannelImpl extends DataSourceImpl implements CommunicationChannel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CommunicationChannelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LowcodersPackage.Literals.COMMUNICATION_CHANNEL;
  }

} //CommunicationChannelImpl
