/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.lowcoders.HybridFeedback;
import org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hybrid Feedback</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HybridFeedbackImpl extends FeedbackImpl implements HybridFeedback
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HybridFeedbackImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LowcodersPackage.Literals.HYBRID_FEEDBACK;
  }

} //HybridFeedbackImpl
