/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.lowcoders.ImplicitFeedback;
import org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Implicit Feedback</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ImplicitFeedbackImpl extends FeedbackImpl implements ImplicitFeedback
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImplicitFeedbackImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LowcodersPackage.Literals.IMPLICIT_FEEDBACK;
  }

} //ImplicitFeedbackImpl
