/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.lowcoders.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.lowcoders.JupyterNotebook;
import org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Jupyter Notebook</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JupyterNotebookImpl extends PresentationLayerImpl implements JupyterNotebook
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JupyterNotebookImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LowcodersPackage.Literals.JUPYTER_NOTEBOOK;
  }

} //JupyterNotebookImpl
