/**
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.lowcoders.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.lev4recgrammar.first.lowcoders.LowcodersPackage;
import org.xtext.lev4recgrammar.first.lowcoders.TraversableGraph;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Traversable Graph</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TraversableGraphImpl extends PresentationLayerImpl implements TraversableGraph
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TraversableGraphImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LowcodersPackage.Literals.TRAVERSABLE_GRAPH;
  }

} //TraversableGraphImpl
