/*
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RsDslUiModule extends AbstractRsDslUiModule {

	public RsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
