/*
 * generated by Xtext 2.29.0
 */
package org.xtext.lev4recgrammar.first.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRsDslScopeProvider extends DelegatingScopeProvider {
}
