/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Validation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.ContextValidation#getTestContext <em>Test Context</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getContextValidation()
 * @model
 * @generated
 */
public interface ContextValidation extends ValidationTechnique
{
  /**
   * Returns the value of the '<em><b>Test Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Context</em>' reference.
   * @see #setTestContext(RecommendationContext)
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getContextValidation_TestContext()
   * @model
   * @generated
   */
  RecommendationContext getTestContext();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.rsDsl.ContextValidation#getTestContext <em>Test Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test Context</em>' reference.
   * @see #getTestContext()
   * @generated
   */
  void setTestContext(RecommendationContext value);

} // ContextValidation
