/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Recommender</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.CustomRecommender#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.CustomRecommender#getRequiredTools <em>Required Tools</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getCustomRecommender()
 * @model
 * @generated
 */
public interface CustomRecommender extends RecommendationSystem
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getCustomRecommender_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.rsDsl.CustomRecommender#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Required Tools</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required Tools</em>' attribute list.
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getCustomRecommender_RequiredTools()
   * @model unique="false"
   * @generated
   */
  EList<String> getRequiredTools();

} // CustomRecommender
