/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Mining RS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.DataMiningRS#getDataMiningRSAlgorithm <em>Data Mining RS Algorithm</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getDataMiningRS()
 * @model
 * @generated
 */
public interface DataMiningRS extends RecommendationSystem
{
  /**
   * Returns the value of the '<em><b>Data Mining RS Algorithm</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.rsDsl.DataMiningRSAlgorithm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Mining RS Algorithm</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.rsDsl.DataMiningRSAlgorithm
   * @see #setDataMiningRSAlgorithm(DataMiningRSAlgorithm)
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getDataMiningRS_DataMiningRSAlgorithm()
   * @model
   * @generated
   */
  DataMiningRSAlgorithm getDataMiningRSAlgorithm();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.rsDsl.DataMiningRS#getDataMiningRSAlgorithm <em>Data Mining RS Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Mining RS Algorithm</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.rsDsl.DataMiningRSAlgorithm
   * @see #getDataMiningRSAlgorithm()
   * @generated
   */
  void setDataMiningRSAlgorithm(DataMiningRSAlgorithm value);

} // DataMiningRS
