/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GUI Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getGUIElement()
 * @model
 * @generated
 */
public interface GUIElement extends EObject
{
} // GUIElement
