/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hybrid Feedback</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getHybridFeedback()
 * @model
 * @generated
 */
public interface HybridFeedback extends Feedback
{
} // HybridFeedback
