/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Presentation Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.PresentationLayer#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.PresentationLayer#getRecommendations <em>Recommendations</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getPresentationLayer()
 * @model
 * @generated
 */
public interface PresentationLayer extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getPresentationLayer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.rsDsl.PresentationLayer#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Recommendations</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recommendations</em>' reference.
   * @see #setRecommendations(RecommendedItem)
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getPresentationLayer_Recommendations()
   * @model
   * @generated
   */
  RecommendedItem getRecommendations();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.rsDsl.PresentationLayer#getRecommendations <em>Recommendations</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recommendations</em>' reference.
   * @see #getRecommendations()
   * @generated
   */
  void setRecommendations(RecommendedItem value);

} // PresentationLayer
