/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Raw Outcomes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lev4recgrammar.first.rsDsl.RawOutcomes#getFormat <em>Format</em>}</li>
 * </ul>
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getRawOutcomes()
 * @model
 * @generated
 */
public interface RawOutcomes extends PresentationLayer
{
  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lev4recgrammar.first.rsDsl.RawFormat}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.rsDsl.RawFormat
   * @see #setFormat(RawFormat)
   * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getRawOutcomes_Format()
   * @model
   * @generated
   */
  RawFormat getFormat();

  /**
   * Sets the value of the '{@link org.xtext.lev4recgrammar.first.rsDsl.RawOutcomes#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see org.xtext.lev4recgrammar.first.rsDsl.RawFormat
   * @see #getFormat()
   * @generated
   */
  void setFormat(RawFormat value);

} // RawOutcomes
