/**
 * generated by Xtext 2.23.0
 */
package org.xtext.lev4recgrammar.first.rsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unsupervised Dataset</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.lev4recgrammar.first.rsDsl.RsDslPackage#getUnsupervisedDataset()
 * @model
 * @generated
 */
public interface UnsupervisedDataset extends Dataset
{
} // UnsupervisedDataset
